create table if not exists public.students (
  id text primary key,
  nis text,
  name text not null,
  class_name text not null,
  gender text check (gender in ('Laki-laki', 'Perempuan') or gender is null),
  username text unique not null,
  password text not null default '123',
  created_at timestamptz not null default now()
);

create table if not exists public.attendances (
  id text primary key,
  student_id text not null references public.students(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  date date not null,
  time text not null,
  status text not null default 'Hadir',
  created_at timestamptz not null default now(),
  unique (student_id, date)
);

create table if not exists public.holidays (
  date date primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.sync_changes (
  id bigint generated by default as identity primary key,
  table_name text not null check (table_name in ('students', 'attendances', 'holidays')),
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  record_id text not null,
  record_date date,
  student_id text,
  row_data jsonb not null,
  changed_at timestamptz not null default now()
);

create or replace function public.get_server_time()
returns timestamptz
language sql
stable
as $$ select now(); $$;

grant execute on function public.get_server_time() to anon, authenticated;

alter table public.students enable row level security;
alter table public.attendances enable row level security;
alter table public.holidays enable row level security;
alter table public.sync_changes enable row level security;

-- Temporary policies for the current username/password flow.
-- Replace these with authenticated-user policies before production launch.
drop policy if exists "public can read students" on public.students;
drop policy if exists "public can insert students" on public.students;
drop policy if exists "public can update students" on public.students;
drop policy if exists "public can delete students" on public.students;
drop policy if exists "public can read attendances" on public.attendances;
drop policy if exists "public can insert attendances" on public.attendances;
drop policy if exists "public can update attendances" on public.attendances;
drop policy if exists "public can delete attendances" on public.attendances;
drop policy if exists "public can read holidays" on public.holidays;
drop policy if exists "public can insert holidays" on public.holidays;
drop policy if exists "public can delete holidays" on public.holidays;
create policy "public can read students" on public.students for select using (true);
create policy "public can insert students" on public.students for insert with check (true);
create policy "public can update students" on public.students for update using (true) with check (true);
create policy "public can delete students" on public.students for delete using (true);
create policy "public can read attendances" on public.attendances for select using (true);
create policy "public can insert attendances" on public.attendances for insert with check (true);
create policy "public can update attendances" on public.attendances for update using (true) with check (true);
create policy "public can delete attendances" on public.attendances for delete using (true);
create policy "public can read holidays" on public.holidays for select using (true);
create policy "public can insert holidays" on public.holidays for insert with check (true);
create policy "public can delete holidays" on public.holidays for delete using (true);
drop policy if exists "public can read sync changes" on public.sync_changes;
create policy "public can read sync changes" on public.sync_changes for select using (true);

grant select on public.sync_changes to anon, authenticated;

create index if not exists attendances_date_idx on public.attendances(date);
create index if not exists attendances_student_idx on public.attendances(student_id);
create index if not exists sync_changes_table_id_idx on public.sync_changes(table_name, id);
create index if not exists sync_changes_record_date_id_idx on public.sync_changes(record_date, id);
create index if not exists sync_changes_student_id_id_idx on public.sync_changes(student_id, id);
create index if not exists sync_changes_changed_at_idx on public.sync_changes(changed_at);

create or replace function public.capture_sync_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  payload jsonb;
  payload_id text;
  payload_date date;
  payload_student_id text;
begin
  if tg_op = 'DELETE' then
    payload := to_jsonb(old);
  else
    payload := to_jsonb(new);
  end if;

  payload_id := coalesce(payload ->> 'id', payload ->> 'date');
  if tg_table_name = 'attendances' then
    payload_date := (payload ->> 'date')::date;
    payload_student_id := payload ->> 'student_id';
  elsif tg_table_name = 'holidays' then
    payload_date := (payload ->> 'date')::date;
  elsif tg_table_name = 'students' then
    payload_student_id := payload ->> 'id';
  end if;

  insert into public.sync_changes (
    table_name,
    operation,
    record_id,
    record_date,
    student_id,
    row_data
  ) values (
    tg_table_name,
    tg_op,
    payload_id,
    payload_date,
    payload_student_id,
    payload
  );

  delete from public.sync_changes
  where changed_at < now() - interval '30 days';

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke execute on function public.capture_sync_change() from public, anon, authenticated;

drop trigger if exists students_sync_changes on public.students;
create trigger students_sync_changes
  after insert or update or delete on public.students
  for each row execute function public.capture_sync_change();

drop trigger if exists attendances_sync_changes on public.attendances;
create trigger attendances_sync_changes
  after insert or update or delete on public.attendances
  for each row execute function public.capture_sync_change();

drop trigger if exists holidays_sync_changes on public.holidays;
create trigger holidays_sync_changes
  after insert or update or delete on public.holidays
  for each row execute function public.capture_sync_change();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'students'
  ) then alter publication supabase_realtime add table public.students; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'attendances'
  ) then alter publication supabase_realtime add table public.attendances; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'holidays'
  ) then alter publication supabase_realtime add table public.holidays; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sync_changes'
  ) then alter publication supabase_realtime add table public.sync_changes; end if;
end $$;
