create table if not exists public.students (
  id text primary key,
  nis text,
  name text not null,
  class_name text not null,
  gender text check (gender in ('Laki-laki', 'Perempuan') or gender is null),
  username text unique not null,
  password text not null default '123',
  created_at timestamptz not null default now()
);

create table if not exists public.attendances (
  id text primary key,
  student_id text not null references public.students(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  date date not null,
  time text not null,
  status text not null default 'Hadir',
  created_at timestamptz not null default now(),
  unique (student_id, date)
);

create table if not exists public.holidays (
  date date primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.prayer_schedule (
  id integer primary key check (id = 1),
  enabled boolean not null default true,
  start_time time not null default '11:30',
  end_time time not null default '15:00',
  constraint prayer_schedule_time_order check (start_time < end_time)
);

insert into public.prayer_schedule (id) values (1) on conflict (id) do nothing;

create table if not exists public.sync_changes (
  id bigint generated by default as identity primary key,
  table_name text not null check (table_name in ('students', 'attendances', 'holidays')),
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  record_id text not null,
  record_date date,
  student_id text,
  row_data jsonb not null,
  changed_at timestamptz not null default now()
);

create or replace function public.get_server_time()
returns timestamptz
language sql
stable
set search_path = pg_catalog
as $$ select now(); $$;

grant execute on function public.get_server_time() to anon, authenticated;

create or replace function public.get_monthly_class_prayer_ranking(
  p_month date,
  p_class_name text default null
)
returns table (
  class_name text,
  student_count bigint,
  sholat_count bigint,
  haid_count bigint,
  absent_count bigint,
  expected_attendance bigint,
  percentage numeric
)
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  with bounds as (
    select
      date_trunc('month', p_month)::date as start_date,
      (date_trunc('month', p_month) + interval '1 month - 1 day')::date as end_date
  ), month_days as (
    select (end_date - start_date + 1)::bigint as days
    from bounds
  ), class_students as (
    select
      s.class_name,
      count(*)::bigint as student_count
    from public.students s
    where p_class_name is null or s.class_name = p_class_name
    group by s.class_name
  ), class_attendances as (
    select
      a.class_name,
      count(a.id) filter (where a.status <> 'Haid')::bigint as sholat_count,
      count(a.id) filter (where a.status = 'Haid')::bigint as haid_count,
      count(a.id)::bigint as attendance_count
    from public.attendances a
    cross join bounds b
    where a.date >= b.start_date
      and a.date <= b.end_date
      and (p_class_name is null or a.class_name = p_class_name)
    group by a.class_name
  )
  select
    cs.class_name,
    cs.student_count,
    coalesce(ca.sholat_count, 0) as sholat_count,
    coalesce(ca.haid_count, 0) as haid_count,
    greatest((cs.student_count * md.days) - coalesce(ca.attendance_count, 0), 0) as absent_count,
    cs.student_count * md.days as expected_attendance,
    round(
      case
        when cs.student_count * md.days = 0 then 0
        else coalesce(ca.sholat_count, 0)::numeric * 100 / (cs.student_count * md.days)
      end,
      1
    ) as percentage
  from class_students cs
  cross join month_days md
  left join class_attendances ca on ca.class_name = cs.class_name
  order by percentage desc, sholat_count desc, cs.class_name asc;
$$;

revoke execute on function public.get_monthly_class_prayer_ranking(date, text) from public;
grant execute on function public.get_monthly_class_prayer_ranking(date, text) to anon, authenticated;

notify pgrst, 'reload schema';

alter table public.students enable row level security;
alter table public.attendances enable row level security;
alter table public.holidays enable row level security;
alter table public.prayer_schedule enable row level security;
alter table public.sync_changes enable row level security;

-- Temporary policies for the current username/password flow.
-- Replace these with authenticated-user policies before production launch.
drop policy if exists "public can read students" on public.students;
drop policy if exists "public can insert students" on public.students;
drop policy if exists "public can update students" on public.students;
drop policy if exists "public can delete students" on public.students;
drop policy if exists "public can read attendances" on public.attendances;
drop policy if exists "public can insert attendances" on public.attendances;
drop policy if exists "public can update attendances" on public.attendances;
drop policy if exists "public can delete attendances" on public.attendances;
drop policy if exists "public can read holidays" on public.holidays;
drop policy if exists "public can insert holidays" on public.holidays;
drop policy if exists "public can delete holidays" on public.holidays;
drop policy if exists "public can read prayer schedule" on public.prayer_schedule;
drop policy if exists "public can update prayer schedule" on public.prayer_schedule;
create policy "public can read students" on public.students for select using (true);
create policy "public can insert students" on public.students for insert with check (true);
create policy "public can update students" on public.students for update using (true) with check (true);
create policy "public can delete students" on public.students for delete using (true);
create policy "public can read attendances" on public.attendances for select using (true);
create policy "public can insert attendances" on public.attendances for insert with check (true);
create policy "public can update attendances" on public.attendances for update using (true) with check (true);
create policy "public can delete attendances" on public.attendances for delete using (true);
create policy "public can read holidays" on public.holidays for select using (true);
create policy "public can insert holidays" on public.holidays for insert with check (true);
create policy "public can delete holidays" on public.holidays for delete using (true);
create policy "public can read prayer schedule" on public.prayer_schedule for select using (true);
create policy "public can update prayer schedule" on public.prayer_schedule for update using (true) with check (true);
grant select, update on public.prayer_schedule to anon, authenticated;
drop policy if exists "public can read sync changes" on public.sync_changes;
create policy "public can read sync changes" on public.sync_changes for select using (true);

grant select on public.sync_changes to anon, authenticated;

create index if not exists attendances_date_idx on public.attendances(date);
create index if not exists attendances_student_idx on public.attendances(student_id);
create index if not exists attendances_class_date_idx on public.attendances(class_name, date);
create index if not exists students_class_name_idx on public.students(class_name, name);
create index if not exists sync_changes_table_id_idx on public.sync_changes(table_name, id);
create index if not exists sync_changes_record_date_id_idx on public.sync_changes(record_date, id);
create index if not exists sync_changes_student_id_id_idx on public.sync_changes(student_id, id);
create index if not exists sync_changes_changed_at_idx on public.sync_changes(changed_at);

create or replace function public.capture_sync_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  payload jsonb;
  payload_id text;
  payload_date date;
  payload_student_id text;
begin
  if tg_op = 'DELETE' then
    payload := to_jsonb(old);
  else
    payload := to_jsonb(new);
  end if;

  payload_id := coalesce(payload ->> 'id', payload ->> 'date');
  if tg_table_name = 'attendances' then
    payload_date := (payload ->> 'date')::date;
    payload_student_id := payload ->> 'student_id';
  elsif tg_table_name = 'holidays' then
    payload_date := (payload ->> 'date')::date;
  elsif tg_table_name = 'students' then
    payload_student_id := payload ->> 'id';
  end if;

  insert into public.sync_changes (
    table_name,
    operation,
    record_id,
    record_date,
    student_id,
    row_data
  ) values (
    tg_table_name,
    tg_op,
    payload_id,
    payload_date,
    payload_student_id,
    payload
  );

  delete from public.sync_changes
  where changed_at < now() - interval '30 days';

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke execute on function public.capture_sync_change() from public, anon, authenticated;

do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    revoke execute on function public.rls_auto_enable() from public, anon, authenticated;
  end if;
end $$;

drop trigger if exists students_sync_changes on public.students;
create trigger students_sync_changes
  after insert or update or delete on public.students
  for each row execute function public.capture_sync_change();

drop trigger if exists attendances_sync_changes on public.attendances;
create trigger attendances_sync_changes
  after insert or update or delete on public.attendances
  for each row execute function public.capture_sync_change();

drop trigger if exists holidays_sync_changes on public.holidays;
create trigger holidays_sync_changes
  after insert or update or delete on public.holidays
  for each row execute function public.capture_sync_change();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'students'
  ) then alter publication supabase_realtime add table public.students; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'attendances'
  ) then alter publication supabase_realtime add table public.attendances; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'holidays'
  ) then alter publication supabase_realtime add table public.holidays; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sync_changes'
  ) then alter publication supabase_realtime add table public.sync_changes; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'prayer_schedule'
  ) then alter publication supabase_realtime add table public.prayer_schedule; end if;
end $$;
